# Generated by Django 3.2.4 on 2021-06-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_alter_theme_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='parent',
        ),
    ]
