# Generated by Django 3.2.4 on 2021-06-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_remove_theme_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='parent',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='parent',
            new_name='theme',
        ),
    ]
